### ISSUE TITLE
npc text is not updating when join.

### ISSUE THREAD

**Issue by Chibilena** [MinecraftLibraries/NPCLib#100]
If I spawn an NPC I can easily update the text, as soon as a player joint and I assign the NPC as visible the text will not be updated live to the player.

**Comment by Chibilena** [comment]
the text ist updating just the hologram is not updating

**Comment by JitseB** [comment]
Please use the provided issue template. Closing ticket for now.

You can post the issue template (found [here](https://github.com/MinecraftLibraries/NPCLib/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)), then the issue ticket will be reopened.
