### ISSUE TITLE
R3 causing problems 

### ISSUE THREAD

**Issue by lackoSK** [MinecraftLibraries/NPCLib#102]
**Describe the bug**
When loading the plugin, will say version unsupported however I can see R3 package inside the lib. 

**NPCLib JAR name**
npclib-plugin-2.8-SNAPSHOT.jar

**Server version**
![image](https://user-images.githubusercontent.com/53174757/86567254-55cb1580-bf6b-11ea-8218-65111e088bfa.png)

**To Reproduce**
- Start the server with lib registered 

**Expected behavior**
Run the plugin 

**Screenshots**
![image](https://user-images.githubusercontent.com/53174757/86567187-3502c000-bf6b-11ea-866b-d1106a9a6fe2.png)
![image](https://user-images.githubusercontent.com/53174757/86567197-3c29ce00-bf6b-11ea-8ae6-d22466f29a3a.png)

**Comment by JitseB** [comment]
Can you provide your usage option?

To me it seems that you're using the API file instead of the Plugin file, as the implementation can't be found.

**Comment by lackoSK** [comment]
I do not use this lib any longer, switched to other which works fine
