### ISSUE TITLE
1_8_R3 stopped working

### ISSUE THREAD

**Issue by skylerush** [MinecraftLibraries/NPCLib#103]
1_8_R3:
[12:46:45] [Server thread/INFO]: NPCLib Attempting to inject into netty
[12:46:45] [Server thread/ERROR]: Error occurred while enabling plugin v2.0.0 (Is it up to date?)
java.lang.RuntimeException: Cannot invoke method public net.minecraft.server.v1_8_R3.WorldServer org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getHandle()
	at com.comphenix.tinyprotocol.Reflection.lambda$0(Reflection.java:231) ~[?:?]
	at net.jitse.npclib.hologram.Hologram.<init>(Hologram.java:89) ~[?:?]

**Comment by skylerush** [comment]
PaperSpigot is no longer supported ti this library

**Comment by JitseB** [comment]
Hm. I've looked at the source code of PaperSpigot (https://yivesmirror.com/grab/paper/PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest), which seems to support that method just fine. Are you using another vendor?

> PaperSpigot is no longer supported ti this library
Source?

**Comment by JitseB** [comment]
I can't reproduce your error, that's why I'm asking these questions.

Could you comment on those? Your latest comment doesn't contribute to solving the issue.

**Comment by skylerush** [comment]
This server is running Paper version git-Paper-235 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
This is the jar file and this happens on multiple versions but works done on spigot

**Comment by skylerush** [comment]
Fine***

**Comment by JitseB** [comment]
That's not 1.8 R2, that's 1.15 R1. I'll look again, thanks.
(For your next issue ticket, please use the provided issue template)

**Comment by skylerush** [comment]
fixed, in a new version of the library was required an update
