### ISSUE TITLE
Head Rotation assembly

### ISSUE THREAD

**Issue by skylerush** [MinecraftLibraries/NPCLib#107]
soo this library is very nice soo I thought to contribute to this project and fix the Head Rotation situation.
This is a work in progress**
[Video of the work](https://imgur.com/gbGMEqK)

**Comment by JitseB** [comment]
Looking good! If you create a PR, I could probably be of some help. I've made such an assembly in the past.

**Comment by rjammet** [comment]
Where is the development? ;)

**Comment by JitseB** [comment]
Added in latest release.
