### ISSUE TITLE
why no official discord?

### ISSUE THREAD

**Issue by pluttotv** [MinecraftLibraries/NPCLib#109]
theres alot of people using this amazing api. 
alot of people who want to share, contribute, talk and w/e amazing stuff that could be achieve with this plugin api.

why not creating a discord for it?

**Comment by JitseB** [comment]
I would’ve never thought people would want a Discord server for this library. Though, I’m eager to give it a try!

The link to the Discord server is: https://discord.gg/pvJGhEq 
I’ll also post it on the repo’s README.

**Comment by JitseB** [comment]
Closing ticket.
