### ISSUE TITLE
Plugin not loading in 1.16.2

### ISSUE THREAD

**Issue by Daschi1** [MinecraftLibraries/NPCLib#118]
**Describe the bug**
When the API gets loaded it gives an error in the console that `1.16.2` is not supported even though the latest version is listed for adding support to `1.16.2`.

**NPCLib usage option**
3

**Server version**
`git-Paper-161 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)`

**To Reproduce**
- Used code  `NPCLib npcLib = new NPCLib(this);`
- See error `NPCLib Failed to initiate. Your server's version (v1_16_R2) is not supported`

**Expected behavior**
The plugin version `2.10-SNAPSHOT` should work with `1.16.2`.

**Comment by JitseB** [comment]
Support added in latest release.
