### ISSUE TITLE
1.16.4 support

### ISSUE THREAD

**Issue by Damien0503** [MinecraftLibraries/NPCLib#125]
**Describe the bug**
1.16.4 is just not supported :)

**NPCLib usage option**
2

**NPCLib JAR name**
npclib-plugin-2.10-SNAPSHOT.jar

**Server version**
Paper 1.16.4 (build 260)

**To Reproduce**
Just start a server in 1.16.4

**Comment by Mooselk** [comment]
I don’t think much has changed since 1.16.2 so you could probably copy paste the 1.16r1 class and rename it and the version enum to MinecraftVersion https://github.com/MinecraftLibraries/NPCLib/blob/master/api/src/main/java/net/jitse/npclib/internal/MinecraftVersion.java

**Comment by hacecah555** [comment]
packets are changed, please check if you can do something for 1.16.4 thank you. :)

**Comment by Mooselk** [comment]
I’ll create a pull request when I get the chance.

**Comment by Mooselk** [comment]
https://github.com/Mooselk/NPCLib/releases/tag/2.9.1

**Comment by JitseB** [comment]
I will post the official release in a bit.
