### ISSUE TITLE
Multiple states toggle wrong state

### ISSUE THREAD

**Issue by Mooselk** [MinecraftLibraries/NPCLib#129]
**Describe the bug**
Toggling state with 2+ active states toggles wrong state. Might be toggling first state in the collection. 

**NPCLib JAR name**
npclib-plugin-2.11-SNAPSHOT.jar

**To Reproduce**

// toggle 2 states 
npc.toggleState(NPCState.ON_FIRE);
npc.toggleState(NPCState.CROUCHED);

// toggles crouch instead of fire
npc.toggleState(NPCState.ON_FIRE);

**Expected behavior**
Toggle state fire should toggle state fire instead of crouched and vice versa.

**Comment by JitseB** [comment]
Merged PR, closing issue. If the issue is not fixed, the issue may be reopened.
