### ISSUE TITLE
npc.setText method doesn't work.

### ISSUE THREAD

**Issue by andrei923** [MinecraftLibraries/NPCLib#134]
**Describe the bug**
npc.setText method doesn't work, no error, it does not update the text of the NPC.
npc.getText() returns the setted text.

**NPCLib usage option**
shaded in the plugin.

**NPCLib JAR name**
E.g. npclib-plugin-2.11.1-SNAPSHOT.jar 

**Server version**
spigot 1.8.8

**To Reproduce**
NPC npc = library.createNPC();
npc.setLocation(Location location);
npc.create();
npc.show(Player player);
npc.setText(Arrays.asList("test" and "test2"))

**Comment by JitseB** [comment]
I see. Working on a fix right now.

**Comment by JitseB** [comment]
Could you try the pre release, version 2.12-SNAPSHOT. Issue should be resolved. I will release a stable version next week.

Closing issue for now.
