### ISSUE TITLE
error when deleting the plugin

### ISSUE THREAD

**Issue by nikillo99** [MinecraftLibraries/NPCLib#137]
I installed the plugin and it gave me an error when configuring it so I tried to delete it and it won't let me, it won't let me delete it in any way

**Comment by JitseB** [comment]
What do you mean? First of all, NPCLib is not a plugin, it is a library. The plugin file serves solely as a class loader. When a server is turned off, you should be able to remove that file just as any other plugin.

**Comment by JitseB** [comment]
Closing issue for now due to inactivity.
