### ISSUE TITLE
I have a error in the console

### ISSUE THREAD

**Issue by Angxstupst** [MinecraftLibraries/NPCLib#138]
Describe the bug
Error in the console

Server version
Paper-Spigot 1.8.8

Exception in thread "pool-8-thread-1"
[SpeedCW-1][23:48:00 WARN]: java.lang.NullPointerException
[SpeedCW-1][23:48:00 WARN]:     at de.universalcw.main.npc.NPCManager.lambda$loadNPC$0(NPCManager.java:32)
[SpeedCW-1][23:48:00 WARN]:     at de.universalcw.main.npc.api.skin.MineSkinFetcher.lambda$fetchSkinFromIdAsync$0(MineSkinFetcher.java:49)
[SpeedCW-1][23:48:00 WARN]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[SpeedCW-1][23:48:00 WARN]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[SpeedCW-1][23:48:00 WARN]:     at java.lang.Thread.run(Thread.java:748)
[SpeedCW-1][23:48:00 WARN]: Exception in thread "pool-8-thread-2"
[SpeedCW-1][23:48:00 WARN]: java.lang.NullPointerException
[SpeedCW-1][23:48:00 WARN]:     at de.universalcw.main.npc.NPCManager.lambda$loadNPC$0(NPCManager.java:32)
[SpeedCW-1][23:48:00 WARN]:     at de.universalcw.main.npc.api.skin.MineSkinFetcher.lambda$fetchSkinFromIdAsync$0(MineSkinFetcher.java:49)
[SpeedCW-1][23:48:00 WARN]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[SpeedCW-1][23:48:00 WARN]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[SpeedCW-1][23:48:00 WARN]:     at java.lang.Thread.run(Thread.java:748)

**Comment by JitseB** [comment]
Closed, please use provided issue template.

**Comment by Angxstupst** [comment]
Here is my pom.xml: https://pastebin.com/Eeqhu0s2

**Comment by Angxstupst** [comment]
That doesn't help. The mistake keeps coming back
