### ISSUE TITLE
NPCs are displayed in the tablist

### ISSUE THREAD

**Issue by Angxstupst** [MinecraftLibraries/NPCLib#143]
**Describe the bug**
As soon as the player can no longer see the NPCs (from the field of view), and then goes
back to the NPCs, the NPCs will be displayed again in the tab. Is that deactivable?

**NPCLib usage option**
Maven dependency

**NPCLib JAR name**
E.g. npclib-plugin-2.11.1-SNAPSHOT.jar

**Server version**
CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by JitseB** [comment]
No, this cannot be prevented. I made them dark-gray so that they're visible as little as possible. However the reason has to do with the order in which packets need to be send to create the fake players.

Closing issue.
