### ISSUE TITLE
[Poll] Discord Invite Link Invalid

### ISSUE THREAD

**Issue by Swedz** [MinecraftLibraries/NPCLib#149]
The discord invite link on the spigot page and on the readme are no longer valid. Can we get a permanent invite link? Thanks :)

**Comment by JitseB** [comment]
I deleted the server about a year ago, since I am not very active on Discord anymore. My main communication for the library is through the GitHub ticket system.

**Comment by JitseB** [comment]
I would like to do a little poll: If this messages gets 20 thumbs up within a month, I'll create a new Discord server for developers to talk on. Keep in mind the previous message I posted.

**Comment by JitseB** [comment]
Closing...
