### ISSUE TITLE
Lib fails to initiate ("v1_12_R1 is not supported")

### ISSUE THREAD

**Issue by Cosmiiko** [MinecraftLibraries/NPCLib#161]
**Describe the bug**
Lib fails to initiate on my Paper 1.12.2 server.
`[13:54:46 ERROR]: NPCLib Failed to initiate. Your server's version (v1_12_R1) is not supported`

**NPCLib usage option**
Maven dep + repo + shading. Configured the same way as in the readme.

**NPCLib JAR name**
N/A

**Server version**
 This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**To Reproduce**
Doubt it's easily reproductible as it should be supported...
Add plugin as meven dep on your project, and init the lib in the plugin's main class (with `npcLib = new NPCLib(this);`) like in the provided examples.

**Expected behavior**
Plugin should load normally.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Cosmiiko** [comment]
Nevermind, this is a dupe of https://github.com/MinecraftLibraries/NPCLib/issues/72.
I'm an idiot.

**Comment by JitseB** [comment]
No worries, happy coding!
