### ISSUE TITLE
No such methode?

### ISSUE THREAD

**Issue by TUBEOF** [MinecraftLibraries/NPCLib#74]
Hey, i get this error on startup:
https://pastebin.com/yhYqa1SD

I have also tried it with your example codes, but its not working :/
My Main Class:
https://pastebin.com/AMFsxauw

**Comment by JitseB** [comment]
Hi, thanks for opening this ticket!

It seems to me that the location you’re tying to spawn the NPC at is null. Can you verify this?

**Comment by JitseB** [comment]
Closed due to inactivity. Ticket may be reopened any time.
