### ISSUE TITLE
Can't see NPC since latest version

### ISSUE THREAD

**Issue by thisisfel1x** [MinecraftLibraries/NPCLib#75]
Hey,
so today, I updated my plugin to the latest version of your API (2.6), hoping for some improvements with the Tab. But when I join my server, it just shows the headline of the npc, not the npc itself.
I have not changed anything in the code

**NPCLib JAR name**
npclib-plugin-2.6-SNAPSHOT.jar

**Server version**
Paper-1.8.8

** Screenshot **
[CLICK](https://imgur.com/a/F1Hz9f2)

**Comment by thisisfel1x** [comment]
bump

**Comment by JitseB** [comment]
No need to bump, I’ve seen your ticket. I’ve just been too busy to reply to it.

There should be no reason for this issue to occur. I’ve tested it before publishing the new release. Is this something that always happens to all NPCs? Or just a select few at some random time?

**Comment by thisisfel1x** [comment]
Sorry for bump. :c
This happens to all my NPCs. I'll try to reinstall my server

**Comment by thisisfel1x** [comment]
fixed

**Comment by JitseB** [comment]
No worries. Glad it’s fixed now.
Have a good day!
