### ISSUE TITLE
forceLabyModEmote# throws noclassdefexception

### ISSUE THREAD

**Issue by CedricDevelopment** [MinecraftLibraries/NPCLib#78]
**Describe the bug**
i want to play an emote on my npc with labymod but it just throws a noclassdefexception.

**NPCLib usage option**
2

**NPCLib JAR name**
NPCLib.jar

**Server version**
CraftBukkit version git-Spigot-db6de12-18fbb24

**To Reproduce**
CODE:

    @EventHandler
    public void onJoin(PlayerJoinEvent e){
        Bukkit.getServer().getScheduler().scheduleSyncDelayedTask(main.getInstance(), ()->{
           Bukkit.getScheduler().runTask(main.getInstance(), () -> myNPC.show(e.getPlayer()));
            Bukkit.getScheduler().scheduleSyncRepeatingTask(main.getInstance(), new Runnable() {
                @Override
                public void run() {
                        myNPC.forceLabyModEmote(e.getPlayer(), 2);
                }
            }, 0, 200L);
        }, 60L);
    }

**Screenshots**
https://prnt.sc/s3wgpv

**Additional context**

**Comment by JitseB** [comment]
Hi, thanks for opening this ticket.

The class should just exist (https://github.com/MinecraftLibraries/NPCLib/blob/master/api/src/main/java/net/labymod/utilities/LMCUtils.java) is included in the building process.

Are you using version 2.6?

**Comment by thisisfel1x** [comment]
This also happens for me. I don't shade the Library in the plugin, but I have it in the plugins folder. Same Error

**Comment by CedricDevelopment** [comment]
yes i am using version 2.6

**Comment by JitseB** [comment]
I don’t understand why it wouldn’t work. The class it’s referring to is shaded in to the plugin, I just checked.
Do you have any other plugins installed on your server that might interfere with this?

**Comment by CedricDevelopment** [comment]
I just made a new Plugin with your Lib on a new Server with only my Plugin and yours...
Everything is working completely fine except the forceLabyModEmote# was still throwing a NoClassDefException...

**Comment by CedricDevelopment** [comment]
Is it possible to get the UUID of the NPC so we can use the normal LabyModAPI?

**Comment by JitseB** [comment]
Ah, well I could make that happen. I was waiting for a response to PR #77, but this seems like am appropriate reason to merge it.

I’ll soon post an update with the `NPC#getUniqueId` method.

**Comment by JitseB** [comment]
You can download the new release with the new method here: https://github.com/MinecraftLibraries/NPCLib/releases/tag/2.7-SNAPSHOT
Cheers!
