### ISSUE TITLE
can't get NPC#getUniqueID

### ISSUE THREAD

**Issue by CedricDevelopment** [MinecraftLibraries/NPCLib#80]
**Describe the bug**
it's not possible to get the UUID of the NPC. Maybe the getUniqueID method is not included in the NPC Interface?

**NPCLib usage option**
2.7

**NPCLib JAR name**
npclib-plugin-2.7-SNAPSHOT

**Comment by JitseB** [comment]
Ah. Silly me. I implemented it, but forgot to add it to the API. Thanks for creating this ticket! Will soon be solved.
