### ISSUE TITLE
repackage isn't really working :\

### ISSUE THREAD

**Issue by skylerush** [MinecraftLibraries/NPCLib#82]
**Describe the bug**
soo I renamed the entire classes packages
tried to run both plugins each one uses different classpaths

also, I will note that running them separate 
one is off and one is on
works fine

**NPCLib JAR name**
E.g. npclib-plugin-2.7-SNAPSHOT.jar

**Server version**
E.g. CraftBukkit version git-Spigot-a1f2566-97b0057 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT) (use command `/version`)

27.04 11:26:25 [Server] Server thread/ERROR NPCLib Failed to initiate. Your server's version (v1_15_R1) is not supported
27.04 11:26:25 [Server] Server thread/WARN NPCLib Failed to create NPC. Please report the following stacktrace message
27.04 11:26:25 [Server] INFO java.lang.NullPointerException: null
27.04 11:26:25 [Server] INFO at plugin.net.jitse.npclib.NPCLib.createNPC(NPCLib.java:112) [plugin.jar:?]
27.04 11:26:25 [Server] INFO at sagi.plugin.prewait.prewait.spawn(prewait.java:39) [plugin.jar:?]
27.04 11:26:25 [Server] INFO at sagi.plugin.Timers.waitingPhase.run(waitingPhase.java:52) [plugin.jar:?]
27.04 11:26:25 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) [Spigot-1.15.2.jar:git-Spigot-a03b1fd-fc318cc]
27.04 11:26:25 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [Spigot-1.15.2.jar:git-Spigot-a03b1fd-fc318cc]
27.04 11:26:25 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [Spigot-1.15.2.jar:git-Spigot-a03b1fd-fc318cc]
27.04 11:26:25 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [Spigot-1.15.2.jar:git-Spigot-a03b1fd-fc318cc]
27.04 11:26:25 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [Spigot-1.15.2.jar:git-Spigot-a03b1fd-fc318cc]
27.04 11:26:25 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [Spigot-1.15.2.jar:git-Spigot-a03b1fd-fc318cc]

**Comment by JitseB** [comment]
This is a totally different error. What code are you using to spawn the NPC?

**Comment by skylerush** [comment]
-> line 39 this.npc = new NPCLib(pl).createNPC(name);
			
Skin skin = new Skin(pl.getConfig().getString("texture.Data"), pl.getConfig().getString("texture.Singature"));
this.npc.setSkin(skin);

String world = pl.getConfig().getString("location.World");
Double x = pl.getConfig().getDouble("location.X");
Double y = pl.getConfig().getDouble("location.Y");
Double z = pl.getConfig().getDouble("location.Z");
float yaw = (float) pl.getConfig().getDouble("location.Yaw");
float pitch =(float) pl.getConfig().getDouble("location.Pitch");

Location loc = new Location(Bukkit.getWorld(world), x, y, z, yaw, pitch);

this.npc.setLocation(loc);

this.npc.create();


** Please note that the plugins work while the other is not loaded entirely (even not on the server folder (plugins))

**Comment by skylerush** [comment]
name var is ArrayList

**Comment by JitseB** [comment]
The reason for this to occur is that you didn't change this line: https://github.com/MinecraftLibraries/NPCLib/blob/master/api/src/main/java/net/jitse/npclib/NPCLib.java#L34

You should port this to the right class as well.

**Comment by JitseB** [comment]
Related to both #87 and #79
