### ISSUE TITLE
Could not pass event PlayerQuitEvent null

### ISSUE THREAD

**Issue by skylerush** [MinecraftLibraries/NPCLib#83]
**Describe the bug**
Error accure on playerQuitEvent

**NPCLib usage option**

**NPCLib JAR name**
E.g. npclib-plugin-2.7-SNAPSHOT.jar

**Server version**
E.g. CraftBukkit version git-Spigot-a1f2566-97b0057 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT) (use command `/version`)

**To Reproduce**
Quit The game while you have NPC..

**Expected behavior**
not to shot this error

**Screenshots**
https://mcpaste.io/1139ec3d9ab47884

**Comment by EazyFTW** [comment]
Can confirm I got the same exact error: https://i.eazyftw.com/MVXoEqg.java

**Comment by JitseB** [comment]
Solved in PR #88, will soon post a version of NPCLib with the updated code.
