### ISSUE TITLE
Solution offering formultiple plugins JVM loading

### ISSUE THREAD

**Issue by skylerush** [MinecraftLibraries/NPCLib#87]
https://stackoverflow.com/questions/482633/in-java-is-it-possible-to-know-whether-a-class-has-already-been-loaded
I did some investigating journalism and I found that thread that can detect if the library is already loaded
and if soo use the current loading version if not load It!

**Comment by skylerush** [comment]
#82

**Comment by JitseB** [comment]
Thanks! I'll look into this.

**Comment by JitseB** [comment]
So, the answer is yes and no. I could indeed use this to check if the library is loaded multiple times. Yes, this could definitely work for servers that run the library as a plugin on the server. There's only one instance of the class in this case. We just want to load another 'slave' of the same instance.

However, most developers use Maven to shade the library. This will undoubtedly cause issues like #79, which I sadly can't do anything about at the moment.

For a new major release of NPCLib, I'll have to take this into account. Either the library should be able to be ported to a new package or I should just convert it to a standalone plugin, removing this problem altogether and use the loader as described above.

For now, you can use the solution I brought up in #79.

Best of luck! (and I'll keep this in mind when redesigning the library for the next major release). 💻
