### ISSUE TITLE
Fetch Skin - Connection timed out

### ISSUE THREAD

**Issue by rjammet** [MinecraftLibraries/NPCLib#92]
Hi!

My plugin works perfectly, until I make a minor change (not the Librery NPC). So my plugin relaunches and the fix works, however, after the server restart, an error occurs when the NPCs must appear. Apparently it would be a timed out of the connection to read the data on the API of the MineSkin site.

However no changes were made, I even put back my old plugin and now no more NPC can spawning as long as the connection timed out. I have not found any solutions to fix it, so if someone can enlighten me on this big problem.

Contents problem > Connection timed out, URLConnection,

(In the method `fetchSkinFromIdAsync(int id, Callback callback) { }` the line `httpURLConnection.connect();` is source.
But if i try to go in the website with this id, i have all the necessary data to have texture skin.

Here is the error code:
https://prnt.sc/sqrl1p

Good evening to you !

**Comment by JitseB** [comment]
It's possible that the Mineskin API is not online at all times!

I recommend you to fetch the skin data only once and save it in a text file in your server's files. That way you'll come across such issues less often. (If the skin could not be fetched successfully on first try, try it some x amount of time later using a repeating task that self-cancels when it's successfully fetched).
