### ISSUE TITLE
NPC's sometimes not spawning

### ISSUE THREAD

**Issue by HyperSkys** [MinecraftLibraries/NPCLib#93]
Sometimes the NPC's will just not spawn in some cases as I use NPCLib in my bedwars server some players cannot access the NPC Shop as it doesn't spawn!

Anyway we can fix this
It does this on every version!

Thanks, it is a random thing just happens!

**Comment by JitseB** [comment]
Hi, I see this is your first issue ever created. I have added an issue template so I can solve your issue best. As you've not done this, I'll close this issue until you've posted the necessary information.
(you may find it here: https://github.com/MinecraftLibraries/NPCLib/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)
