### ISSUE TITLE
NPCs not removed from tablist after reload 1.16.1

### ISSUE THREAD

**Issue by Jocke155** [MinecraftLibraries/NPCLib#99]
**Describe the bug**
Reloading the server causes newly created NPCs to get stuck in the tablist. They are never removed, but logging out and in fixes the issue.

**NPCLib usage option**
2

**NPCLib JAR name**
npclib-plugin-2.8-SNAPSHOT

**Server version**
This server is running CraftBukkit version git-Spigot-4d9262c-dc7c3c6 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**To Reproduce**
- Used Example 3 to create them async. onDisable I destroy the NPCs ,and create new ones async onEnable.
- Reload the server (/reload)
- See the NPCs in the tablist, they are never removed.

_If you reload the server multiple times, even more NPCs remain on the tablist._

**Expected behavior**
That the NPCs are removed from the tablist.

**Screenshots**
_Taken in a separate world from where they are created. If I stand next to them the issue is the same, but the difference in this picture is that the show method is never called._
![image](https://user-images.githubusercontent.com/21155583/86509760-859edf80-bdea-11ea-9a2e-271a801d9241.png)

**Comment by EazyFTW** [comment]
Are you doing /rl confirm? Or actually reloading the server.

**Comment by Jocke155** [comment]
> Are you doing /reload? Or actually restarting the server.

I'm doing /reload

**Comment by EazyFTW** [comment]
Rejoin. That's the reason. There's no code removing the NPCs on reload. I don't necessarily think this is a bug. I think it's intended.

**Comment by Jocke155** [comment]
> Rejoin. That's the reason. There's no code removing the NPCs on reload. I don't necessarily think this is a bug. I think it's intended.

I never had these problems in 1.15 though. Also, I do destroy the NPCs onDisable as I described in the issue. The problem is that they are appearing in the scoreboard once they are created again during onEnable, and never seem to get removed so if you reload many times, the number of NPCs on the scoreboard is just increasing every time.

**Comment by EazyFTW** [comment]
Hm... weird. I'll leave this to Jitse then.

**Comment by JitseB** [comment]
Every time you reload the server, all NPCs are recreated, therefore getting a new tab-list entry. It might be that in 1.16 post-disable packets have been removed (wouldn't know why). Is the console spitting out any errors?

Also, if you destroy the NPC on another event (not onDisable), do the tab-list entries go away?

**Comment by Jocke155** [comment]
No errors in console.

I tried putting the onDisable and onEnable calls on a command instead, and the issue remains, once the new ones are created there are duplicates in the tab-list that are not removed when I destroy the NPCs.

**Comment by JitseB** [comment]
Are you showing the NPCs async to the players as well?

**Comment by Jocke155** [comment]
They are shown sync, but this happens no matter if they are shown to the player or not. (I do a world check before showing)

**Comment by JitseB** [comment]
Well I'll try to keep this in mind whilst redesigning the library in the future. For now, NPCLib doesn't fully support reloading (it's better to restart in any case but that's my opinion). Reloading is more something you'd do in a development environment.
